export default {
  login: "kalinahr",
  avatar_url: "https://avatars.githubusercontent.com/u/94054407?v=4",
  url: "https://api.github.com/users/kalinahr",
  html_url: "https://github.com/kalinahr",
  followers_url: "https://api.github.com/users/kalinahr/followers",
  following_url: "https://api.github.com/users/kalinahr/following{/other_user}",
  gists_url: "https://api.github.com/users/kalinahr/gists{/gist_id}",
  starred_url: "https://api.github.com/users/kalinahr/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/userskalinahr//subscriptions",
  organizations_url: "https://api.github.com/users/kalinahr/orgs",
  repos_url: "https://api.github.com/users/kalinahr/repos",
  events_url: "https://api.github.com/users/kalinahr/events{/privacy}",
  received_events_url: "https://api.github.com/users/kalinahr/received_events",
  type: "User",
  site_admin: false,
  name: "khalissa Hebal",
  blog: "https://hashnode.com/@khalissa",
  location: "",
  email: null,
  hireable: null,
  bio: "Frontend developer and designer",
  twitter_username: "@khalissacode",
  public_repos: 10,
  public_gists: 0,
  followers: 8,
  following: 4,
};
